### ISSUE TITLE
1.6.0 Issue on osx when using a pure python backend: wrong glfw or opengl dll being used (rpath issue)

### ISSUE THREAD

**Issue by pthom** [conda-forge/imgui-bundle-feedstock#6]
This issue (with v1.6.0) is similar to https://github.com/conda-forge/imgui-bundle-feedstock/issues/14 (with v1.6.2)

### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Hello Mark,

I just did an extensive test on MacOS arm64 (python 3.12). Everything works flawlessly! 

There are only two issues which I describe below. I'm pretty sure I have a good intuition about where they are coming from, I will give you the explanation below. 

I installed the package like this (after commit 20cfc14e2c3892d73da843088ae0678d69a4e088)

```
conda create --name poub  imgui-bundle pillow python=3.12 opencv="*=headless*" --channel=conda-forge --override-channels
conda activate poub
imgui_bundle_demo
```

Unimportant note: after the install, I had this message
```
SafetyError: The package for imgui-bundle located at /Users/pascal/miniconda3/pkgs/imgui-bundle-1.6.0-py312h65e5808_1
appears to be corrupted. The path 'lib/python3.12/site-packages/imgui_bundle/demos_python/demos_node_editor/romeo_and_juliet.json'
has an incorrect size.
  reported size: 354 bytes
  actual size: 353 bytes
```

### Errors with glfw

Then, I run the demo, and launch "immediate apps/example_python_backend_glfw3.py"
![Image](https://github.com/user-attachments/assets/2cd8f99d-f57b-46c8-b3b0-4ec42e5e8057)

At first try, it will not run because the python module glfw cannot be found.

```
Traceback (most recent call last):
  File "/Users/pascal/miniconda3/envs/poub/lib/python3.12/site-packages/imgui_bundle/python_backends/examples/example_python_backend_glfw3.py", line 9, in <module>
    from imgui_bundle.python_backends.glfw_backend import GlfwRenderer
  File "/Users/pascal/miniconda3/envs/poub/lib/python3.12/site-packages/imgui_bundle/python_backends/glfw_backend.py", line 5, in <module>
    import glfw  # type: ignore
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'glfw'
```

I installed it
```
pip install glfw
```

Then it complains a second time about
```
    import OpenGL.GL as gl  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'OpenGL'
```

Which I installed with
```
conda install pyopengl
```

Then I try again, and I get the dll error message:

```
(poub) ➜  poub.poub objc[88812]: Class GLFWHelper is implemented in both 
/Users/pascal/miniconda3/envs/poub/lib/libglfw.3.4.dylib (0x102e45b28) 
and 
/Users/pascal/miniconda3/envs/poub/lib/python3.12/site-packages/glfw/libglfw.3.dylib (0x1052b9bb8). 

One of the two will be used. Which one is undefined.
... 
```
and then the application raises a hard segfault.

I remember I had solved this issue by adjusting the rpath:

https://github.com/pthom/imgui_bundle/blob/9909fc4ba7196e9be95084cd897749b3f5cd08bc/imgui_bundle_cmake/internal/add_imgui_bundle_bindings.cmake#L1-L10
```
# Set the rpath for Linux and  MacOS (see https://github.com/pybind/cmake_example/issues/11)
function(_target_set_rpath target relative_path)
    set_target_properties(${target} PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE)
    if(UNIX AND NOT APPLE)
        set_target_properties(${target} PROPERTIES INSTALL_RPATH "$ORIGIN/${relative_path}/")
    elseif(APPLE)
        set_target_properties(${target} PROPERTIES INSTALL_RPATH "@loader_path/${relative_path}/")
    endif()
    set_target_properties(${target} PROPERTIES INSTALL_RPATH_USE_LINK_PATH TRUE)
endfunction()
```

### Errors with pyopengl / coming from conda or pip

I then tried the demo 
![Image](https://github.com/user-attachments/assets/d7bb868f-4941-46ef-baa3-9ac4f23e430f)

In order for it to run you need to install pysdl2 (only available via pip)
```
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
```
==>
```
 pip install pysdl2
```

Then you need to install pyopengl (opengl bindings).
```
  File "/Users/pascal/miniconda3/envs/poub/lib/python3.12/site-packages/imgui_bundle/python_backends/opengl_backend.py", line 4, in <module>
    import OpenGL.GL as gl  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'OpenGL'
```
==> You can do it either via
```
pip install pyopengl
# or
conda install pyopengl
```

If you install it via `pip install pyopengl`, the example `example_python_backend_sdl2` will work.

If you install it via `conda install pyopengl`, the example `example_python_backend_sdl2` will not work, and a hard error will be raised:

![Image](https://github.com/user-attachments/assets/ba3f2d06-72a3-47f5-a618-6f165df8be15)

I am almost certain that this is also a rpath issue.

### Installed packages

```shell
conda list
# packages in environment at /Users/pascal/miniconda3/envs/poub:
#
# Name                    Version                   Build  Channel
annotated-types           0.7.0              pyhd8ed1ab_1    conda-forge
aom                       3.9.1                h7bae524_0    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.34.3               h5505292_1    conda-forge
ca-certificates           2024.11.26           hca03da5_0    defaults
cairo                     1.18.2               h6a3b0d2_0    conda-forge
dav1d                     1.2.1                hb547adb_0    conda-forge
ffmpeg                    7.1.0           gpl_h92f8dbd_105    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h1383a14_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
gdk-pixbuf                2.42.12              h7ddc832_0    conda-forge
glfw                      2.8.0                    pypi_0    pypi
gmp                       6.3.0                h7bae524_2    conda-forge
graphite2                 1.3.13            hebf3989_1003    conda-forge
harfbuzz                  9.0.0                h997cde5_1    conda-forge
hdf5                      1.14.3          nompi_ha698983_108    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
imath                     3.1.12               h025cafa_0    conda-forge
imgui-bundle              1.6.0           py312h65e5808_1    conda-forge
jasper                    4.2.4                h6c4e4ef_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lame                      3.100             h1a8c8d9_1003    conda-forge
lcms2                     2.16                 ha0e7c42_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20240722.0      cxx17_hf9b8971_1    conda-forge
libaec                    1.1.3                hebf3989_0    conda-forge
libasprintf               0.22.5               h8414b35_3    conda-forge
libass                    0.17.3               hf20b609_0    conda-forge
libblas                   3.9.0           25_osxarm64_openblas    conda-forge
libcblas                  3.9.0           25_osxarm64_openblas    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.5               ha82da77_0    conda-forge
libdeflate                1.22                 hd74edd7_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.4                h286801f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgettextpo              0.22.5               h8414b35_3    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libglib                   2.82.2               h07bd6cf_0    conda-forge
libhwloc                  2.11.2          default_hbce5d74_1001    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libintl                   0.22.5               h8414b35_3    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           25_osxarm64_openblas    conda-forge
liblapacke                3.9.0           25_osxarm64_openblas    conda-forge
liblzma                   5.6.3                h39f12f2_1    conda-forge
liblzma-devel             5.6.3                h39f12f2_1    conda-forge
libnghttp2                1.64.0               h6d7220d_0    conda-forge
libopenblas               0.3.28          openmp_hf332438_1    conda-forge
libopencv                 4.10.0          headless_py312h86a6ccd_11    conda-forge
libopenvino               2024.4.0             hbfeda7a_2    conda-forge
libopenvino-arm-cpu-plugin 2024.4.0             hbfeda7a_2    conda-forge
libopenvino-auto-batch-plugin 2024.4.0             hf276634_2    conda-forge
libopenvino-auto-plugin   2024.4.0             hf276634_2    conda-forge
libopenvino-hetero-plugin 2024.4.0             h03892cd_2    conda-forge
libopenvino-ir-frontend   2024.4.0             h03892cd_2    conda-forge
libopenvino-onnx-frontend 2024.4.0             h7f5a098_2    conda-forge
libopenvino-paddle-frontend 2024.4.0             h7f5a098_2    conda-forge
libopenvino-pytorch-frontend 2024.4.0             h5833ebf_2    conda-forge
libopenvino-tensorflow-frontend 2024.4.0             h9d544f2_2    conda-forge
libopenvino-tensorflow-lite-frontend 2024.4.0             h5833ebf_2    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
libprotobuf               5.28.2               h8f0b736_0    conda-forge
librsvg                   2.58.4               h40956f1_0    conda-forge
libsqlite                 3.47.0               hbaaea75_1    conda-forge
libssh2                   1.11.1               h9cc3647_0    conda-forge
libtiff                   4.7.0                ha962b0a_2    conda-forge
libvpx                    1.14.1               h7bae524_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.17.0               hdb1d25a_0    conda-forge
libxml2                   2.13.5               h178c5d8_1    conda-forge
libzlib                   1.3.1                h8359307_2    conda-forge
llvm-openmp               19.1.5               hdb05f8b_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
numpy                     2.2.0           py312h41c6370_0    conda-forge
opencv                    4.10.0          headless_py312h13aeb2b_11    conda-forge
openexr                   3.3.2                h04410fd_0    conda-forge
openh264                  2.5.0                h774163f_0    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.4.0                h39f12f2_0    conda-forge
pango                     1.54.0               h9ee27a3_2    conda-forge
pcre2                     10.44                h297a79d_2    conda-forge
pillow                    11.0.0          py312haf37ca6_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pixman                    0.44.2               h2f9eb0b_0    conda-forge
plutosvg                  0.0.3                h86f3900_0    conda-forge
plutovg                   0.0.9                h5505292_0    conda-forge
pthread-stubs             0.4               hd74edd7_1002    conda-forge
pugixml                   1.14                 h13dd4ca_0    conda-forge
py-opencv                 4.10.0          headless_py312hfcc5adf_11    conda-forge
pydantic                  2.10.3             pyh3cfb1c2_0    conda-forge
pydantic-core             2.27.1          py312hcd83bfe_0    conda-forge
pyglet                    2.0.20                   pypi_0    pypi
pyopengl                  3.1.1a1         py312hca03da5_0    defaults
pysdl2                    0.9.16                   pypi_0    pypi
pysdl2-dll                2.30.9                   pypi_0    pypi
python                    3.12.8          hc22306f_1_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
snappy                    1.2.1                h98b9ce2_1    conda-forge
svt-av1                   2.3.0                hf24288c_0    conda-forge
tbb                       2022.0.0             h0cbf7ec_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
typing-extensions         4.12.2               hd8ed1ab_1    conda-forge
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
x264                      1!164.3095           h57fd34a_2    conda-forge
x265                      3.5                  hbc6ce65_3    conda-forge
xorg-libxau               1.0.11               hd74edd7_1    conda-forge
xorg-libxdmcp             1.1.5                hd74edd7_0    conda-forge
xz                        5.6.3                h9a6d368_1    conda-forge
xz-gpl-tools              5.6.3                h9a6d368_1    conda-forge
xz-tools                  5.6.3                h39f12f2_1    conda-forge
zlib                      1.3.1                h8359307_2    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
active environment : poub
    active env location : /Users/pascal/miniconda3/envs/poub
            shell level : 2
       user config file : /Users/pascal/.condarc
 populated config files : /Users/pascal/miniconda3/.condarc
                          /Users/pascal/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.9.2=0
                          __osx=15.1.1=0
                          __unix=0=0
       base environment : /Users/pascal/miniconda3  (writable)
      conda av data dir : /Users/pascal/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/pascal/miniconda3/pkgs
                          /Users/pascal/.conda/pkgs
       envs directories : /Users/pascal/miniconda3/envs
                          /Users/pascal/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Darwin/24.1.0 OSX/15.1.1 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
```
pip install glfw
```
should not be used

I think the pyopengl issues are going to be resolved with 3.1.7 soon to be released on conda-forge.

I believe that this is due to some ABI incompatibilities in the pip package, something htat is resolved by conda packages.

**Comment by pthom** [comment]
Hi Mark,

I think we can close this issue, as it was for 1.6.0 (now superseeded by 1.6.2), and its solution should be to install 
```
conda install -c mark.harfouche pyopengl
```

as for the related issue #14

**Comment by hmaarrfk** [comment]
FYI 
I merged the conda forge version of pyopengl so that it is now up to date. Please check to ensure that it is true.

**Comment by pthom** [comment]
I just did a test:

This works:

```
(poub) ➜  ~ conda list | grep opengl
pyopengl                  3.1.7              pyhd8ed1ab_0    mark.harfouche
```

This also works:

```
(poub) ➜  ~ conda list | grep opengl
pyopengl                  3.1.7              pyhd8ed1ab_0    conda-forge
```


And this fails:

```
(poub) ➜  ~ conda list | grep opengl
pyopengl                  3.1.1a1         py313hca03da5_0    defaults
```


So I guess, it is ok
