### ISSUE TITLE
Test report on Win x64 Python 3.12 - Install conflict between conda and pip for sdl and glfw?

### ISSUE THREAD

**Issue by pthom** [conda-forge/imgui-bundle-feedstock#8]
Hello again Mark,

I finished the test by running on Windows. Everything is running very smoothly, including freetype.

However, I encountered an issue when running an application which uses a pure python backend (be it glfw or sdl2): I get errors saying "no module named 'glfw'" or "no module named 'sdl2'".

---
### Error reproduction

I created an environment like this:
```
conda create --name poub  imgui-bundle pillow python=3.12 opencv="*=headless*" --channel=conda-forge --override-channels
conda activate poub
```
Then tried to run this demo
![Image](https://github.com/user-attachments/assets/2d325e92-1d36-4cb7-a0e5-c9b92d60dc98)

And I got this error
```
Traceback (most recent call last):
  File "C:\Users\pascal\anaconda3\envs\poub\Lib\site-packages\imgui_bundle\demos_python/demos_immapp/imgui_example_glfw_opengl3.py", line 20, in <module>
    import glfw  # type: ignore
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'glfw'
```

Which I tried to solve with:
```
pip install glfw
```

But it was not enough, I still get the error:
```
Traceback (most recent call last):
  File "C:\Users\pascal\anaconda3\envs\poub\Lib\site-packages\imgui_bundle\demos_python/demos_immapp/imgui_example_glfw_opengl3.py", line 20, in <module>
    import glfw  # type: ignore
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'glfw'
```

Then I tried to run this demo:
![Image](https://github.com/user-attachments/assets/2f490486-9b2b-43c8-a9c4-c49376214cd9)

Even though I did install pysdl2 (and its separate dll), like this
```
pip install pysdl2 pysdl2-dll
```
I still get the error:
```
  File "C:\Users\pascal\anaconda3\envs\poub\Lib\site-packages\imgui_bundle\python_backends\sdl_backend.py", line 7, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
```

---

### Environment info

```
(poub) C:\Users\pascal>pip list
Package                    Version
-------------------------- -----------
anaconda-client            1.12.3
archspec                   0.2.3
asttokens                  2.4.1
attrs                      24.2.0
beautifulsoup4             4.12.3
boltons                    24.0.0
Brotli                     1.1.0
certifi                    2024.8.30
cffi                       1.17.1
chardet                    5.2.0
charset-normalizer         3.4.0
click                      8.1.7
colorama                   0.4.6
comm                       0.2.2
conda                      24.11.0
conda-build                24.11.2
conda_forge_ci_setup       4.13.0
conda-forge-metadata       0.11.0
conda_index                0.5.0
conda-libmamba-solver      24.11.1
conda-oci-mirror           0.0.0
conda-package-handling     2.4.0
conda_package_streaming    0.11.0
debugpy                    1.8.2
decorator                  5.1.1
defusedxml                 0.7.1
Deprecated                 1.2.15
distro                     1.9.0
executing                  2.0.1
fastjsonschema             2.21.1
filelock                   3.16.1
frozendict                 2.4.6
glfw                       2.8.0
h2                         4.1.0
hpack                      4.0.0
hyperframe                 6.0.1
idna                       3.10
importlib_resources        6.4.5
ipykernel                  6.29.5
ipython                    8.26.0
jedi                       0.19.1
Jinja2                     3.1.4
joblib                     1.4.2
jsonpatch                  1.33
jsonpointer                3.0.0
jsonschema                 4.23.0
jsonschema-specifications  2024.10.1
jupyter_client             8.6.2
jupyter_core               5.7.2
libarchive-c               5.1
libmambapy                 2.0.4
lief                       0.14.1
MarkupSafe                 3.0.2
matplotlib-inline          0.1.7
menuinst                   2.2.0
more-itertools             10.5.0
nbformat                   5.10.4
nest-asyncio               1.6.0
networkx                   2.4
oras                       0.1.14
packaging                  24.1
parso                      0.8.4
pip                        24.3.1
pkginfo                    1.12.0
pkgutil_resolve_name       1.3.10
platformdirs               4.2.2
pluggy                     1.5.0
prompt_toolkit             3.0.47
psutil                     6.0.0
pure-eval                  0.2.2
pycosat                    0.6.6
pycparser                  2.22
Pygments                   2.18.0
PySocks                    1.7.1
python-dateutil            2.9.0.post0
pytz                       2024.2
pywin32                    306
PyYAML                     6.0.2
pyzmq                      26.0.3
rattler-build-conda-compat 1.2.2
referencing                0.35.1
requests                   2.32.3
requests-toolbelt          1.0.0
rpds-py                    0.22.3
ruamel.yaml                0.18.6
ruamel.yaml.clib           0.2.8
setuptools                 75.6.0
shyaml                     0.6.2
six                        1.16.0
soupsieve                  2.5
stack-data                 0.6.3
tomli                      2.2.1
tornado                    6.4.1
tqdm                       4.67.1
traitlets                  5.14.3
truststore                 0.10.0
typing_extensions          4.12.2
urllib3                    2.2.3
wcwidth                    0.2.13
wheel                      0.45.1
win_inet_pton              1.1.0
wrapt                      1.17.0
zipp                       3.21.0
zstandard                  0.23.0
```

```
(poub) C:\Users\pascal>conda info

     active environment : poub
    active env location : C:\Users\pascal\anaconda3\envs\poub
            shell level : 2
       user config file : C:\Users\pascal\.condarc
 populated config files : C:\Users\pascal\anaconda3\.condarc
                          C:\Users\pascal\.condarc
          conda version : 24.11.0
    conda-build version : 24.9.0
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.11.0=0
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\Users\pascal\anaconda3  (writable)
      conda av data dir : C:\Users\pascal\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\pascal\anaconda3\pkgs
                          C:\Users\pascal\.conda\pkgs
                          C:\Users\pascal\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\pascal\anaconda3\envs
                          C:\Users\pascal\.conda\envs
                          C:\Users\pascal\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.11.0 requests/2.32.3 CPython/3.12.7 Windows/11 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.8 aau/0.4.4 c/9789hsxxfWVkMFhQi1LwFg s/SlmJUccp1_9ZDd4XyvXE1A e/31lT4r0Qyfa_1ukph8Rpxg
          administrator : False
             netrc file : None
           offline mode : False
```

```
>conda list
# packages in environment at C:\Users\pascal\anaconda3\envs\poub:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_1    conda-forge
aom                       3.9.1                he0c23c2_0    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.11.26           haa95532_0    defaults
cairo                     1.18.2               h5782bbf_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
ffmpeg                    7.1.0           gpl_ha871990_105    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h765892d_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeglut                  3.2.2                he0c23c2_3    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
gdk-pixbuf                2.42.12              hed59a49_0    conda-forge
glfw                      3.4                  hcfcfb64_0    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
harfbuzz                  9.0.0                h2bedf89_1    conda-forge
hdf5                      1.14.3          nompi_hd5d9e70_108    conda-forge
icu                       75.1                 he0c23c2_0    conda-forge
imath                     3.1.12               hbb528cf_0    conda-forge
imgui-bundle              1.6.0           py312hc2f6ac4_1    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
jasper                    4.2.4                hcb1a123_0    conda-forge
khronos-opencl-icd-loader 2024.10.24           h2466b09_1    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20240722.0      cxx17_he0c23c2_1    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libasprintf               0.22.5               h5728263_3    conda-forge
libblas                   3.9.0              25_win64_mkl    conda-forge
libcblas                  3.9.0              25_win64_mkl    conda-forge
libcurl                   8.10.1               h1ee3ff0_0    conda-forge
libdeflate                1.22                 h2466b09_0    conda-forge
libexpat                  2.6.4                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgcc                    14.2.0               h1383e82_1    conda-forge
libgettextpo              0.22.5               h5728263_3    conda-forge
libglib                   2.82.2               h7025463_0    conda-forge
libgomp                   14.2.0               h1383e82_1    conda-forge
libhwloc                  2.11.2          default_ha69328c_1001    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_3    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              25_win64_mkl    conda-forge
liblapacke                3.9.0              25_win64_mkl    conda-forge
liblzma                   5.6.3                h2466b09_1    conda-forge
liblzma-devel             5.6.3                h2466b09_1    conda-forge
libopencv                 4.10.0          headless_py312h1886729_11    conda-forge
libopenvino               2024.4.0             hfe1841e_2    conda-forge
libopenvino-auto-batch-plugin 2024.4.0             h04f32e0_2    conda-forge
libopenvino-auto-plugin   2024.4.0             h04f32e0_2    conda-forge
libopenvino-hetero-plugin 2024.4.0             h372dad0_2    conda-forge
libopenvino-intel-cpu-plugin 2024.4.0             hfe1841e_2    conda-forge
libopenvino-intel-gpu-plugin 2024.4.0             hfe1841e_2    conda-forge
libopenvino-ir-frontend   2024.4.0             h372dad0_2    conda-forge
libopenvino-onnx-frontend 2024.4.0             h7d5e7ba_2    conda-forge
libopenvino-paddle-frontend 2024.4.0             h7d5e7ba_2    conda-forge
libopenvino-pytorch-frontend 2024.4.0             he0c23c2_2    conda-forge
libopenvino-tensorflow-frontend 2024.4.0             h7d689a8_2    conda-forge
libopenvino-tensorflow-lite-frontend 2024.4.0             he0c23c2_2    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.44               h3ca93ac_0    conda-forge
libprotobuf               5.28.2               hcaed137_0    conda-forge
librsvg                   2.58.4               h33bc1f6_0    conda-forge
libsqlite                 3.47.0               h2466b09_1    conda-forge
libssh2                   1.11.1               he619c9f_0    conda-forge
libtiff                   4.7.0                hdefb170_2    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libwinpthread             12.0.0.r4.gg4f2fc60ca      h57928b3_8    conda-forge
libxcb                    1.17.0               h0e4246c_0    conda-forge
libxml2                   2.13.5               he286e8c_1    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
mkl                       2024.2.2            h66d3029_14    conda-forge
munch                     2.5.0              pyhd3eb1b0_0    defaults
numpy                     2.2.0           py312hf10105a_0    conda-forge
opencl-headers            2024.10.24           he0c23c2_0    conda-forge
opencv                    4.10.0          headless_py312hf9a0f71_11    conda-forge
openexr                   3.3.2                h974021d_0    conda-forge
openh264                  2.5.0                ha9db3cd_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.4.0                h2466b09_0    conda-forge
pango                     1.54.0               hbb871f6_2    conda-forge
pcre2                     10.44                h3d7b363_2    conda-forge
pillow                    11.0.0          py312ha41cd45_0    conda-forge
pixman                    0.44.2               had0cd8c_0    conda-forge
plutosvg                  0.0.3                h2099052_0    conda-forge
plutovg                   0.0.9                h2466b09_0    conda-forge
pthread-stubs             0.4               h0e40799_1002    conda-forge
pugixml                   1.14                 h63175ca_0    conda-forge
py-opencv                 4.10.0          headless_py312hc46b06b_11    conda-forge
pydantic                  2.10.3             pyh3cfb1c2_0    conda-forge
pydantic-core             2.27.1          py312h2615798_0    conda-forge
pyglm                     2.7.3           py312hd5eb7cc_1    conda-forge
pyopengl                  3.1.1a1         py312haa95532_0    defaults
python                    3.12.8          h3f84c4b_1_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
setuptools                75.1.0          py312haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snappy                    1.2.1                h500f7fa_1    conda-forge
svt-av1                   2.3.0                he0c23c2_0    conda-forge
tbb                       2021.13.0            h62715c5_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
typing-extensions         4.12.2               hd8ed1ab_1    conda-forge
typing_extensions         4.12.2             pyha770c72_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
vc                        14.3                ha32ba9b_23    conda-forge
vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xorg-libxau               1.0.11               h0e40799_1    conda-forge
xorg-libxdmcp             1.1.5                h0e40799_0    conda-forge
xz                        5.6.3                h208afaa_1    conda-forge
xz-tools                  5.6.3                h2466b09_1    conda-forge
zlib                      1.3.1                h2466b09_2    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

----

### Investigation: is it due to anaconda which installs too many custom pip packages into new environments?

Since I suspect this is not due to your package, but to a mismatch in installation of other packages (pysdl2 and pyGlfw), I tried to create a new environment without anything in it, and to list afterwards they installed conda and PIP packages. 
You will see that, strangely `pip list` gives a heavily populated list right after installing a new environment. This list includes our faulty packages (PySdl2 and glfw)

```
> conda create --name poub3 python=3.12 --channel=conda-forge --override-channels 
> conda activate poub3

> pip list
>pip list
Package                    Version
-------------------------- -----------
anaconda-client            1.12.3
archspec                   0.2.3
asttokens                  2.4.1
attrs                      24.2.0
beautifulsoup4             4.12.3
boltons                    24.0.0
Brotli                     1.1.0
certifi                    2024.8.30
cffi                       1.17.1
chardet                    5.2.0
charset-normalizer         3.4.0
click                      8.1.7
colorama                   0.4.6
comm                       0.2.2
conda                      24.11.0
conda-build                24.11.2
conda_forge_ci_setup       4.13.0
conda-forge-metadata       0.11.0
conda_index                0.5.0
conda-libmamba-solver      24.11.1
conda-oci-mirror           0.0.0
conda-package-handling     2.4.0
conda_package_streaming    0.11.0
debugpy                    1.8.2
decorator                  5.1.1
defusedxml                 0.7.1
Deprecated                 1.2.15
distro                     1.9.0
executing                  2.0.1
fastjsonschema             2.21.1
filelock                   3.16.1
frozendict                 2.4.6
glfw                       2.8.0
h2                         4.1.0
hpack                      4.0.0
hyperframe                 6.0.1
idna                       3.10
importlib_resources        6.4.5
ipykernel                  6.29.5
ipython                    8.26.0
jedi                       0.19.1
Jinja2                     3.1.4
joblib                     1.4.2
jsonpatch                  1.33
jsonpointer                3.0.0
jsonschema                 4.23.0
jsonschema-specifications  2024.10.1
jupyter_client             8.6.2
jupyter_core               5.7.2
libarchive-c               5.1
libmambapy                 2.0.4
lief                       0.14.1
MarkupSafe                 3.0.2
matplotlib-inline          0.1.7
menuinst                   2.2.0
more-itertools             10.5.0
nbformat                   5.10.4
nest-asyncio               1.6.0
networkx                   2.4
oras                       0.1.14
packaging                  24.1
parso                      0.8.4
pip                        24.3.1
pkginfo                    1.12.0
pkgutil_resolve_name       1.3.10
platformdirs               4.2.2
pluggy                     1.5.0
prompt_toolkit             3.0.47
psutil                     6.0.0
pure-eval                  0.2.2
pycosat                    0.6.6
pycparser                  2.22
Pygments                   2.18.0
PySDL2                     0.9.16
pysdl2-dll                 2.30.9
PySocks                    1.7.1
python-dateutil            2.9.0.post0
pytz                       2024.2
pywin32                    306
PyYAML                     6.0.2
pyzmq                      26.0.3
rattler-build-conda-compat 1.2.2
referencing                0.35.1
requests                   2.32.3
requests-toolbelt          1.0.0
rpds-py                    0.22.3
ruamel.yaml                0.18.6
ruamel.yaml.clib           0.2.8
setuptools                 75.6.0
shyaml                     0.6.2
six                        1.16.0
soupsieve                  2.5
stack-data                 0.6.3
tomli                      2.2.1
tornado                    6.4.1
tqdm                       4.67.1
traitlets                  5.14.3
truststore                 0.10.0
typing_extensions          4.12.2
urllib3                    2.2.3
wcwidth                    0.2.13
wheel                      0.45.1
win_inet_pton              1.1.0
wrapt                      1.17.0
zipp                       3.21.0
zstandard                  0.23.0

> conda list
# packages in environment at C:\Users\pascal\anaconda3\envs\poub3:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.8.30            h56e8100_0    conda-forge
libexpat                  2.6.4                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblzma                   5.6.3                h2466b09_1    conda-forge
libsqlite                 3.47.0               h2466b09_1    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
openssl                   3.4.0                h2466b09_0    conda-forge
python                    3.12.8          h3f84c4b_1_cpython    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
vc                        14.3                ha32ba9b_23    conda-forge
vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
```

**Comment by hmaarrfk** [comment]
Sorry for the extremely late reply.

Happy new year!

I left a comment to that effect in the recipe, it seems that the python `glfw` package is only used in a few demos.
Heavy packages get annoying and then stripping them back down becomes difficult since people start to depend on their "mega" dependencies.

In conda-forge land, the name of the package is `pygflw` 
https://github.com/conda-forge/imgui-bundle-feedstock/blob/main/recipe/meta.yaml#L106

```
conda create --name poub  imgui-bundle pyglfw pillow python=3.12 opencv="*=headless*" --channel=conda-forge --override-channels
conda activate poub
```

should resolve things.

This is a bit of the ABI compatibility that I warned against.

Let me know if the addition of pyglfw resolves you particular issues.

<details><summary>lol ubuntu</summary>

I just got this error
```
For information, demos sources are available in /home/mark/miniforge3/envs/poub/lib/python3.12/site-packages/imgui_bundle/demos_python
Traceback (most recent call last):
  File "/home/mark/miniforge3/envs/poub/bin/imgui_bundle_demo", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mark/miniforge3/envs/poub/lib/python3.12/site-packages/imgui_bundle/demos_python/demo_imgui_bundle.py", line 137, in main
    immapp.run(runner_params=runner_params, add_ons_params=addons)
  File "/home/mark/miniforge3/envs/poub/lib/python3.12/site-packages/imgui_bundle/demos_python/demo_imgui_bundle.py", line 78, in win_fn
    show_module_demo(demo_module_name, demo_module.demo_gui)
  File "/home/mark/miniforge3/envs/poub/lib/python3.12/site-packages/imgui_bundle/demos_python/demo_imgui_bundle.py", line 28, in show_module_demo
    demo_function()
  File "/home/mark/miniforge3/envs/poub/lib/python3.12/site-packages/imgui_bundle/demos_python/demo_imgui_show_demo_window.py", line 45, in demo_gui
    imgui.show_demo_window()
RuntimeError: IM_ASSERT( g.CurrentDpiScale > 0.0f && g.CurrentDpiScale < 99.0f )   ---   imgui.cpp:15655
```
need to debug one day.
</details>

**Comment by hmaarrfk** [comment]
I guess one also needs to install

```
pyopengl pysdl2
```

for those last 3 examples.

You can go through
https://conda-forge.org/packages/

The `pyglet` package seems to be a bit problematic for now.

**Comment by hmaarrfk** [comment]
On linux, once one installs all the dependencies from conda-forge 
![Image](https://github.com/user-attachments/assets/0d8213b6-90bd-4408-89db-0090f5eb3bc1)

I had to pick up an experimental build from https://github.com/conda-forge/pyglet-feedstock/pull/101

**Comment by pthom** [comment]
> Sorry for the extremely late reply.

No worries.

> 
> Happy new year!

Happy new year to you too! I've been seriously ill for the last two weeks, but I am now recovering and I'm on a good track.

> 
> I left a comment to that effect in the recipe, it seems that the python `glfw` package is only used in a few demos. Heavy packages get annoying and then stripping them back down becomes difficult since people start to depend on their "mega" dependencies.
> 
> In conda-forge land, the name of the package is `pygflw` https://github.com/conda-forge/imgui-bundle-feedstock/blob/main/recipe/meta.yaml#L106
> 
> ```
> conda create --name poub  imgui-bundle pyglfw pillow python=3.12 opencv="*=headless*" --channel=conda-forge --override-channels
> conda activate poub
> ```
> 
> should resolve things.
> 
> This is a bit of the ABI compatibility that I warned against.
> 
> Let me know if the addition of pyglfw resolves you particular issues.


I cannot test that until I return to Paris in about two weeks. At the moment, I only have a Mac (where I can run Window ARM, but this very niche). I'll let you know.

> lol ubuntu 

This error happens deeps inside ImGui, and only with the full demo. It is **not specific** to conda, and I did solve it with this commit: 
https://github.com/pthom/imgui_bundle/commit/8ae753e0c30df7e0e2a9c791ddc9c171518d86a9
(related issue: https://github.com/pthom/imgui_bundle/issues/293).

This commit is not yet part of an official release. But since you are the third one to mention it, I think it might become worth to release a corrective version 1.6.2

**Comment by hmaarrfk** [comment]
> This error happens deeps inside ImGui, and only with the full demo. It is not specific to conda, and I did solve it with this commit:

Wow! I definitely wasnt expecting that. Thanks!

**Comment by pthom** [comment]
I just released v1.6.2 which should solve the issue you mentioned: 
https://github.com/pthom/imgui_bundle/releases/tag/v1.6.2

(it also add support for ImPlot3D)

**Comment by hmaarrfk** [comment]
I just want to leave this comment since I forgot what the resolution was to this, but it seems that we need to monitor:
https://github.com/conda-forge/pyglet-feedstock/pull/101

to ensure that it gets merged in.

**Comment by pthom** [comment]
Update concerning pyglet: https://github.com/conda-forge/pyglet-feedstock/pull/101 was merged

I just tested that pyglet integration also works with:

```
conda create --name poub  imgui-bundle python=3.12 --channel=conda-forge --override-channels
conda activate poub
conda install pyglet pyopengl --channel=conda-forge
```

Then I can run the demo below (which uses imgui_bundle together with pyglet):

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/9fdf94d3-7ae9-4604-bf56-f5c81f5d9d3c" />

So, I will close this issue since everything is now solved.
